#!/bin/bash

if [[ ! -d doc ]]
then
    mkdir doc && echo "doc directory has been created."
    cd doc
    sphinx-quickstart
else
    echo 'A doc directory already exists.'
fi


# Check if the path to the module is in $PYTHONPATH
# echo $PYTHONPATH | awk -F ':' '{ for (i=1; i < NF; i++)
#                                     if ($i == $PWD) {
#                                     present = 1
#                                     }
# }
