#!/bin/bash

gc() {
    urls="$@"
    open -a Google\ Chrome.app $urls
}

get_cwd( ) {
    echo $PWD | awk -F'/' '{print $(NF)}'        
}

if [[ $(get_cwd) == 'doc' ]] 
then
    # rm -rf 
    make html
    gc _build/html/index.html
fi

