#!/bin/bash

[[ $1 -eq -1 ]] && today=`date +%m/%d/%y` && echo $today
[[ $1 -eq -2 ]] && today=`date +%m-%d-%y` && echo $today
[[ $1 -eq -3 ]] && today=`date +%d/%m/%y` && echo $today
[[ $1 -eq -4 ]] && today=`date +%d-%m-%y` && echo $today

[ $# -ne 1 ] && 
cat <<-EOF 
Usage: today OPTION

Availabe OPTIONs:
-1: m/d/y
-2: m-d-y
-3: d/m/y
-4: d-m-y
EOF
