#!/bin/bash

# Quickly edit your Jekyll posts with Vim.

DATE=$(date "+%Y-%m-%d")
POST_DATE=$(date "+%d %h %Y")
BLOG_PATH=$DROP/DrJekyll/_posts

if [[ $# -gt 0 ]]; then
    TITLE="$@"
    POST=${DATE}-${TITLE}
    LINE=11
else
    POST=
    LINE=1
fi


init_post () {
    echo "---"
    echo "layout: post"
    echo "title: "
    echo "---"
    echo -e "\n"
    echo -e "# {{ page.title }}"
    echo
    echo -e "<p class='meta'> ${POST_DATE} </p>"
    echo -e "\n"
}

init_post > ${BLOG_PATH}/${POST}
vi +$LINE ${BLOG_PATH}/${POST}

